test:
  adapter: sqlite
  database: cas_test.db

development: &ORACLE_TEST_INSTANCE
  adapter: oracle
  host: 'ocs22-scan'
  port: 1521
  username: 'dev_ke4'
  password: 'ke4'
  database: 'cend'

test_ora:
  <<: *ORACLE_TEST_INSTANCE

production:
  adapter: oracle
  host: 'ocs23-scan'
  port: 1521
  username: 'read_only'
  password: 'read_only'
  database: 'casp'
