development_sqlite:
  adapter: sqlite
  database: dev.db

test:
  adapter: sqlite
  database: test.db

test_ora:
  adapter: sqlite
  database: test.db

development_mysql:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: support_development
  username: root
  password: root
  socket: /tmp/mysql.sock

development_jdbc:
  adapter: jdbc
  encoding: utf8
  charset: utf8
  url: mysql://localhost/support_development?user=root&password=

test__:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: test_lims_api
  username: root
  password:
  socket: /tmp/mysql.sock
