require 'lims-support-app/barcode/barcode'
require 'lims-support-app/barcode/create_barcode'
require 'lims-support-app/barcode/bulk_create_barcode'
require 'lims-support-app/barcode/barcode_persistor'
require 'lims-support-app/barcode/barcode_resource'
